export const paths = {
  login: "/login",
  dashboard: "/",
  companies: {
    list: "/companies",
    create: "/companies/new",
    details: (uuid: string) => `/companies/${uuid}`,
    edit: (uuid: string) => `/companies/${uuid}/edit`,
  },
  employees: {
    list: "/employees",
    create: "/employees/new",
    details: (uuid: string) => `/employees/${uuid}`,
    edit: (uuid: string) => `/employees/${uuid}/edit`,
  },
  leads: {
    list: "/leads",
    create: "/leads/new",
    import: "/leads/import",
    assign: "/leads/assign",
    details: (uuid: string) => `/leads/${uuid}`,
    edit: (uuid: string) => `/leads/${uuid}/edit`,
  },
  followups: {
    list: "/followups",
    today: "/followups/today",
    create: "/followups/new",
    edit: (uuid: string) => `/followups/${uuid}/edit`,
    timeline: (uuid: string) => `/followups/${uuid}/timeline`,
    calendar: "/followups/calendar",
  },
  projects: {
    list: "/projects",
    create: "/projects/new",
    inventory: "/projects/inventory",
    details: (uuid: string) => `/projects/${uuid}`,
    edit: (uuid: string) => `/projects/${uuid}/edit`,
    towers: (uuid: string) => `/projects/${uuid}/towers`,
    units: (uuid?: string) => (uuid ? `/projects/${uuid}/units` : "/projects/units"),
  },
  visits: {
    list: "/visits",
    create: "/visits/new",
    details: (uuid: string) => `/visits/${uuid}`,
    edit: (uuid: string) => `/visits/${uuid}/edit`,
    calendar: "/visits/calendar",
  },
  bookings: {
    list: "/bookings",
    create: "/bookings/new",
    approvals: "/bookings/approvals",
    details: (uuid: string) => `/bookings/${uuid}`,
    edit: (uuid: string) => `/bookings/${uuid}/edit`,
    documents: (uuid: string) => `/bookings/${uuid}/documents`,
  },
  notFound: "*",
} as const;
