export const SEED = {
  platform: {
    companyCode: "PLATFORM",
    companyName: "CRM Platform Operations",
    ownerName: "Platform Owner",
    email: "platform@crm-saas.local",
    phone: "9000000001",
    addressLine1: "Platform HQ, Tech Park",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "560001",
    branchCode: "HQ",
    branchName: "Platform Headquarters",
    departmentCode: "OPS",
    departmentName: "Platform Operations",
    designationCode: "PSA",
    designationName: "Platform Super Administrator",
    roleCode: "PLATFORM_SUPER_ADMIN",
    roleName: "Platform Super Admin",
    user: {
      employeeCode: "SA001",
      username: "superadmin",
      password: "Platform@123",
      firstName: "Platform",
      lastName: "Super Admin",
      displayName: "Platform Super Admin",
      officialEmail: "superadmin@crm-saas.local",
      mobile: "9000000001",
    },
  },
  demo: {
    companyCode: "DEMO",
    companyName: "Demo Real Estate Pvt Ltd",
    legalName: "Demo Real Estate Private Limited",
    ownerName: "Demo Owner",
    email: "contact@demo-realestate.local",
    phone: "9000000002",
    addressLine1: "123 MG Road",
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500001",
    branchCode: "MAIN",
    branchName: "Main Branch",
    departmentCode: "ADMIN",
    departmentName: "Administration",
    designationCode: "CA",
    designationName: "Company Administrator",
    roleCode: "COMPANY_ADMIN",
    roleName: "Company Admin",
    user: {
      employeeCode: "ADM001",
      username: "admin",
      password: "Admin@123",
      firstName: "Demo",
      lastName: "Admin",
      displayName: "Demo Company Admin",
      officialEmail: "admin@demo-realestate.local",
      mobile: "9000000002",
    },
  },
} as const;

export const PERMISSIONS = [
  {
    code: "companies.view",
    name: "View Companies",
    module: "companies",
  },
  {
    code: "companies.create",
    name: "Create Companies",
    module: "companies",
  },
  {
    code: "companies.update",
    name: "Update Companies",
    module: "companies",
  },
  {
    code: "companies.delete",
    name: "Delete Companies",
    module: "companies",
  },
  {
    code: "branches.view",
    name: "View Branches",
    module: "branches",
  },
  {
    code: "branches.create",
    name: "Create Branches",
    module: "branches",
  },
  {
    code: "branches.update",
    name: "Update Branches",
    module: "branches",
  },
  {
    code: "branches.delete",
    name: "Delete Branches",
    module: "branches",
  },
  {
    code: "departments.view",
    name: "View Departments",
    module: "departments",
  },
  {
    code: "departments.create",
    name: "Create Departments",
    module: "departments",
  },
  {
    code: "departments.update",
    name: "Update Departments",
    module: "departments",
  },
  {
    code: "departments.delete",
    name: "Delete Departments",
    module: "departments",
  },
  {
    code: "users.view",
    name: "View Users",
    module: "users",
  },
  {
    code: "users.create",
    name: "Create Users",
    module: "users",
  },
  {
    code: "users.update",
    name: "Update Users",
    module: "users",
  },
  {
    code: "users.delete",
    name: "Delete Users",
    module: "users",
  },
  {
    code: "roles.view",
    name: "View Roles",
    module: "roles",
  },
  {
    code: "roles.create",
    name: "Create Roles",
    module: "roles",
  },
  {
    code: "roles.update",
    name: "Update Roles",
    module: "roles",
  },
  {
    code: "roles.delete",
    name: "Delete Roles",
    module: "roles",
  },
] as const;

export const FULL_ACCESS = {
  can_view: true,
  can_create: true,
  can_update: true,
  can_delete: true,
  can_export: true,
  can_approve: true,
} as const;
