export const SEED = {
  platform: {
    companyCode: "PLATFORM",
    companyName: "CRM Platform Operations",
    ownerName: "Platform Owner",
    email: "platform@crm-saas.local",
    phone: "9000000001",
    addressLine1: "Platform HQ, Tech Park",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "560001",
    branchCode: "HQ",
    branchName: "Platform Headquarters",
    departmentCode: "OPS",
    departmentName: "Platform Operations",
    designationCode: "PSA",
    designationName: "Platform Super Administrator",
    roleCode: "PLATFORM_SUPER_ADMIN",
    roleName: "Platform Super Admin",
    user: {
      employeeCode: "SA001",
      username: "superadmin",
      password: "Platform@123",
      firstName: "Platform",
      lastName: "Super Admin",
      displayName: "Platform Super Admin",
      officialEmail: "superadmin@crm-saas.local",
      mobile: "9000000001",
    },
  },
  demo: {
    companyCode: "DEMO",
    companyName: "Demo Real Estate Pvt Ltd",
    legalName: "Demo Real Estate Private Limited",
    ownerName: "Demo Owner",
    email: "contact@demo-realestate.local",
    phone: "9000000002",
    addressLine1: "123 MG Road",
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500001",
    branchCode: "MAIN",
    branchName: "Main Branch",
    departmentCode: "ADMIN",
    departmentName: "Administration",
    designationCode: "CA",
    designationName: "Company Administrator",
    roleCode: "COMPANY_ADMIN",
    roleName: "Company Admin",
    user: {
      employeeCode: "ADM001",
      username: "admin",
      password: "Admin@123",
      firstName: "Demo",
      lastName: "Admin",
      displayName: "Demo Company Admin",
      officialEmail: "admin@demo-realestate.local",
      mobile: "9000000002",
    },
  },
} as const;

export const PERMISSIONS = [
  {
    code: "companies.view",
    name: "View Companies",
    module: "companies",
  },
  {
    code: "companies.create",
    name: "Create Companies",
    module: "companies",
  },
  {
    code: "companies.update",
    name: "Update Companies",
    module: "companies",
  },
  {
    code: "companies.delete",
    name: "Delete Companies",
    module: "companies",
  },
  {
    code: "branches.view",
    name: "View Branches",
    module: "branches",
  },
  {
    code: "branches.create",
    name: "Create Branches",
    module: "branches",
  },
  {
    code: "branches.update",
    name: "Update Branches",
    module: "branches",
  },
  {
    code: "branches.delete",
    name: "Delete Branches",
    module: "branches",
  },
  {
    code: "departments.view",
    name: "View Departments",
    module: "departments",
  },
  {
    code: "departments.create",
    name: "Create Departments",
    module: "departments",
  },
  {
    code: "departments.update",
    name: "Update Departments",
    module: "departments",
  },
  {
    code: "departments.delete",
    name: "Delete Departments",
    module: "departments",
  },
  {
    code: "users.view",
    name: "View Users",
    module: "users",
  },
  {
    code: "users.create",
    name: "Create Users",
    module: "users",
  },
  {
    code: "users.update",
    name: "Update Users",
    module: "users",
  },
  {
    code: "users.delete",
    name: "Delete Users",
    module: "users",
  },
  {
    code: "roles.view",
    name: "View Roles",
    module: "roles",
  },
  {
    code: "roles.create",
    name: "Create Roles",
    module: "roles",
  },
  {
    code: "roles.update",
    name: "Update Roles",
    module: "roles",
  },
  {
    code: "roles.delete",
    name: "Delete Roles",
    module: "roles",
  },
  {
    code: "leads.view",
    name: "View Leads",
    module: "leads",
  },
  {
    code: "leads.create",
    name: "Create Leads",
    module: "leads",
  },
  {
    code: "leads.update",
    name: "Update Leads",
    module: "leads",
  },
  {
    code: "leads.delete",
    name: "Delete Leads",
    module: "leads",
  },
  {
    code: "projects.view",
    name: "View Projects",
    module: "projects",
  },
  {
    code: "projects.create",
    name: "Create Projects",
    module: "projects",
  },
  {
    code: "projects.update",
    name: "Update Projects",
    module: "projects",
  },
  {
    code: "projects.delete",
    name: "Delete Projects",
    module: "projects",
  },
  {
    code: "visits.view",
    name: "View Visits",
    module: "visits",
  },
  {
    code: "visits.create",
    name: "Create Visits",
    module: "visits",
  },
  {
    code: "visits.update",
    name: "Update Visits",
    module: "visits",
  },
  {
    code: "visits.delete",
    name: "Delete Visits",
    module: "visits",
  },
  {
    code: "bookings.view",
    name: "View Bookings",
    module: "bookings",
  },
  {
    code: "bookings.create",
    name: "Create Bookings",
    module: "bookings",
  },
  {
    code: "bookings.update",
    name: "Update Bookings",
    module: "bookings",
  },
  {
    code: "bookings.delete",
    name: "Delete Bookings",
    module: "bookings",
  },
  {
    code: "payments.view",
    name: "View Payments",
    module: "payments",
  },
  {
    code: "payments.create",
    name: "Create Payments",
    module: "payments",
  },
  {
    code: "payments.update",
    name: "Update Payments",
    module: "payments",
  },
  {
    code: "payments.delete",
    name: "Delete Payments",
    module: "payments",
  },
  {
    code: "reports.view",
    name: "View Reports",
    module: "reports",
  },
  {
    code: "reports.export",
    name: "Export Reports",
    module: "reports",
  },
] as const;

export const FULL_ACCESS = {
  can_view: true,
  can_create: true,
  can_update: true,
  can_delete: true,
  can_export: true,
  can_approve: true,
} as const;

export const DEMO_RBAC_ROLES = [
  {
    roleCode: "MANAGER",
    roleName: "Manager",
    designationCode: "MGR",
    designationName: "Sales Manager",
    permissionCodes: [
      "leads.view",
      "leads.create",
      "leads.update",
      "projects.view",
      "visits.view",
      "visits.create",
      "visits.update",
      "bookings.view",
      "bookings.create",
      "bookings.update",
      "payments.view",
      "payments.create",
      "payments.update",
      "reports.view",
      "reports.export",
    ],
    user: {
      employeeCode: "MGR001",
      username: "manager",
      password: "Manager@123",
      firstName: "Demo",
      lastName: "Manager",
      displayName: "Demo Manager",
      officialEmail: "manager@demo-realestate.local",
      mobile: "9000000003",
    },
  },
  {
    roleCode: "TELECALLER",
    roleName: "Telecaller",
    designationCode: "TC",
    designationName: "Telecaller",
    permissionCodes: [
      "leads.view",
      "leads.create",
      "leads.update",
    ],
    user: {
      employeeCode: "TC001",
      username: "telecaller",
      password: "Telecaller@123",
      firstName: "Demo",
      lastName: "Telecaller",
      displayName: "Demo Telecaller",
      officialEmail: "telecaller@demo-realestate.local",
      mobile: "9000000004",
    },
  },
  {
    roleCode: "SALES_EXECUTIVE",
    roleName: "Sales Executive",
    designationCode: "SE",
    designationName: "Sales Executive",
    permissionCodes: [
      "leads.view",
      "leads.update",
      "visits.view",
      "visits.create",
      "visits.update",
      "bookings.view",
      "bookings.create",
      "bookings.update",
      "payments.view",
    ],
    user: {
      employeeCode: "SE001",
      username: "sales",
      password: "Sales@123",
      firstName: "Demo",
      lastName: "Sales",
      displayName: "Demo Sales Executive",
      officialEmail: "sales@demo-realestate.local",
      mobile: "9000000005",
    },
  },
] as const;
